import js from "@eslint/js";

export default [
    js.configs.recommended,
    {
        rules: {
            "arrow-body-style": ["error", "as-needed"],
            "block-scoped-var": "error",
            "camelcase": ["error", { "properties": "never", ignoreDestructuring: true }],
            "curly": ["error", "all"],
            "default-case": "error",
            "default-case-last": "error",
            "dot-notation": "error",
            "eqeqeq": ["error", "always", {"null": "ignore"}],
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-caller": "error",
            "no-else-return": "error",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "no-invalid-this": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-loop-func": "error",
            "no-magic-numbers": ["error", { "ignoreArrayIndexes": true, "ignore": [-1, 0, 1] }],
            "no-multi-assign": "error",
            "no-nested-ternary": "error",
            "no-new-func": "error",
            "no-new-wrappers": "error",
            "no-object-constructor": "error",
            "no-param-reassign": "error",
            "no-plusplus": "error",
            "no-proto": "error",
            "no-return-assign": "error",
            "no-sequences": "error",
            "no-shadow": "error",
            "no-shadow-restricted-names": "error",
            "no-throw-literal": "error",
            "no-undef-init": "error",
            "no-unneeded-ternary": "error",
            "no-unused-expressions": "error",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-var": "error",
            "object-shorthand": "error",
            "one-var": ["error", "never"],
            "prefer-const": "error",
            "prefer-exponentiation-operator": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            "radix": "error",
            "sort-vars": "error",
            "yoda": ["error", "never"]
        }
    }
]