name: Validate PR title

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    permissions:
      contents: read
      pull-requests: write
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            breaking
            chore
            ci
            docs
            feat
            fix
            refactor
            security
            style
            test
