name: Validate PR title

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    permissions:
      contents: read
      pull-requests: write
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: App token
        id: app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.pat_app_id }}
          private_key: ${{ secrets.pat_app_private_key }}

      - name: Validate
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          types: |
            breaking
            chore
            ci
            docs
            feat
            fix
            refactor
            security
            style
            test
